### ISSUE TITLE
Getting SIGABRT when processing bad video

### ISSUE THREAD

**Issue by cedricve** [bakape/thumbnailer#15]
Hey @bakape,

I was just wondering how to properly catch a SIGABRT error. I though by using Notify (signals) but that doesn't seem to work properly. any suggestion?

      Assertion desc failed at libswscale/swscale_internal.h:674
      SIGABRT: abort
      PC=0x7f592d86f1f7 m=4 sigcode=0
      signal arrived during cgo execution

**Comment by bakape** [comment]
We needed to modify signal processing on the C side to prevent crashes of the Go runtime. It was some kind of conflict between Go and GraphicsMagick. See https://github.com/bakape/thumbnailer/blob/master/init.c. Perhaps that is the cause?
