### ISSUE TITLE
Logo contribution for thumbnailer

### ISSUE THREAD

**Issue by reallinfo** [bakape/thumbnailer#25]
Hello!

I want to contribute to open source software by designing logos. If you like, I can design a logo for the restic. What do you think?

I will waiting feedback.

**Comment by bakape** [comment]
This is a small developer-facing library and as such I don't think it needs a logo, but thanks anyway!

**Comment by reallinfo** [comment]
I actually designed a logo. If you want, I can add it to the readme file.  and you need a logo for another project, feel free to say me.

![thumbnailer](https://user-images.githubusercontent.com/36298335/41812270-a495221a-7728-11e8-810f-54e603a90ec6.jpg)
