### ISSUE TITLE
Rewrite thumbnailer in Rust

### ISSUE THREAD

**Issue by Chiiruno** [bakape/thumbnailer#34]
I'll do this, and probably some parts of meguca/hydron too afterwards so we don't have to worry about memory bloat.
This'll take a little while, but I guess give me collaborator permissions on this repo and assign me to this issue.
In the meantime, could you give me some ideas on how thumbnailer could be improved, as well as your thoughts on whether or not we should have different libraries to use?

**Comment by Chiiruno** [comment]
I would do that in C++ at least, for the smart pointers.
That said, honestly I feel Rust might be a better option overall.
Thoughts?

**Comment by bakape** [comment]
Not much point in C++ as most of the code will just be shuffling C APIs.
Rust is also pretty bad at interacting with C (compared to  C++ and Go,
anyway). If you r want to, of course you can write the glue, once I have
the C rewrite done.

**Comment by Chiiruno** [comment]
Rust has some crates for this though, so that shouldn't be an issue.
See:
- https://crates.io/crates/lodepng
- https://crates.io/crates/imagequant
- https://crates.io/crates/imagequant-sys
- https://crates.io/crates/ffmpeg
- https://crates.io/crates/ffmpeg-next
- https://crates.io/crates/ffmpeg-sys
- https://crates.io/crates/gmagick

Not sure about the graphicsmagick one, thoughts?

**Comment by bakape** [comment]
I've tried some of them. Don't remember why I did not use them and just
went with C instead. See, you will have to use C APIs, export a C API and
write some logic code. With Rust, the FFI glue with likely take most of
your code and your logic would still be mostly unafe and thus not protected
by Rust compile-time checks.

**Comment by Chiiruno** [comment]
I'll definitely look into this further, and if that really is the case, I'll close this issue.
I'll also see if there aren't any better rust-specific libraries for this we might be able to use.
I'm doing this to git gud at Rust anyway, so I guess once it's done we can compare and go with whatever works better. (Probably yours honestly, you're a better programmer than me.)

**Comment by Chiiruno** [comment]
Actually, I don't see any particular reason we couldn't just use this library: https://crates.io/crates/image
Have thumbnailer streamline it I guess?

**Comment by bakape** [comment]
I don't see any particular reason to use it either.

**Comment by Chiiruno** [comment]
Well, we (I) wouldn't have to worry about C FFI as much, although I feel that isn't even so much a problem with the crates that exist, sans graphicsmagick.

**Comment by bakape** [comment]
Can you reach functional parity with the current thumbnailer only through
existing crates?

**Comment by Chiiruno** [comment]
I think so, yes, but I can't say for certain right now.
Once I begin implementing, I'll know for sure.
