### ISSUE TITLE
thumbnailer couldn't compile. blur.c no such file or directory

### ISSUE THREAD

**Issue by Miqe** [bakape/thumbnailer#39]
`
vendor/github.com/bakape/thumbnailer/build_flags_gpl.go:7:11: fatal error: blur.c: No such file or directory
 // #include "blur.c"
           ^~~~~~~~
compilation terminated.
`

**Comment by bakape** [comment]
Are you using Go modules? If yes, seems to be related to https://github.com/golang/go/issues/26504
If you happen to find a fix (aside from copying lodepng and imagequant directly into the root dir and losing all submodule version control), let me know.

**Comment by Miqe** [comment]
Yes i am using  Go modules with `dep`. I'll take a look at golang/go#26504
Thanks for replying.

**Comment by bakape** [comment]
Closed with f191a43e9c3c7c9522a67dd81ed1aec9cea0280d
