### ISSUE TITLE
ffmpeg: Invalid data found when processing input

### ISSUE THREAD

**Issue by bakape** [bakape/thumbnailer#50]
Triggered by: 
![bd010adbacde6e9129e51b3bc2aaf80e](https://user-images.githubusercontent.com/7851952/52911933-0f601280-32b3-11e9-8049-895f79a0404c.jpg)

**Comment by Chiiruno** [comment]
Relevant lines: https://github.com/bakape/thumbnailer/blob/master/ffmpeg.c#L28-L31

**Comment by Chiiruno** [comment]
https://stackoverflow.com/questions/21549829/ffmpeg-avformat-open-input-returned-error

**Comment by bakape** [comment]
That's a completely different error code though.

**Comment by Chiiruno** [comment]
WHAT DID YOU EXPECT
WE NEED BETTER DEVS

**Comment by bakape** [comment]
@Chiiruno Interestingly `ffmpeg -i 52911933-0f601280-32b3-11e9-8049-895f79a0404c.jpg test.png` works just fine with some warnings. Could you inspect what is done differently there or should I do it?

**Comment by Chiiruno** [comment]
No idea where to start, will probably save time/effort with you doing checking it.
Right off the bat though, maybe because it's not resizing, or significantly  changing the context?

**Comment by bakape** [comment]
From experience, it probably does some extra thing, that we do not. If what
you said about it being triggered on avformat_open_input is  true, then
resizing has nothing to do with it and we need to inspect how other parts
of the FFmpeg codebase call this function.

>

**Comment by bakape** [comment]
Idea: might be solved with format hints from MIME type detection, if this is the input opening failing automatic format detection.
