### ISSUE TITLE
Add support for comicbook archives

### ISSUE THREAD

**Issue by gen2brain** [bakape/thumbnailer#51]
Comicbook archives are just zip/rar/7z/tar archives with images inside. Readers usually just take a list of files in archives, sort it in a natural order and take the first image, usually that one is the correct cover image.

This is the list of mimetypes:
```
application/x-cbz
application/vnd.comicbook+zip

application/x-cbr
application/vnd.comicbook-rar

application/x-cb7
application/x-cbt
```

I have a wrapper for `unarr` here https://github.com/gen2brain/go-unarr that can be used (it has a bug with LZMA2 currently) or in native Go https://github.com/mholt/archiver (doesn't have 7z support, but such comic books are rare anyway).

**Comment by bakape** [comment]
Is there any way to detect these formats, aside from unzipping and inspecting contents?

**Comment by gen2brain** [comment]
I think possible just by matching file extension, `cbr`, `cbz`, `cb7` and `cbt`. It is just archive with images, and sometimes also some .txt files included.

**Comment by gen2brain** [comment]
And sometimes cover is named `cover.jpg` or `cover.bmp`, usually, all image formats are supported, i.e. jpg, png,  gif, tiff and bmp.

**Comment by bakape** [comment]
This library is meant to be usable with unknown client-uploaded files. Thus I want to avoid detection based on extension as an attack vector.

**Comment by gen2brain** [comment]
Ok, I understand. You can probably then check if file is archive (i.e. magic bytes), then check for cbr,cbz et c. and if positive list archive contents, match extensions/mimetypes and if all or most are images then sort list of files and take first image or cover, and check finally if that file is a real image.

**Comment by bakape** [comment]
None of these files have a strict included metadata spec, correct? So I take it there is no harm in identifying any zip archive with just a bunch of images in it as CBZ (and the same for other archive types)?

**Comment by gen2brain** [comment]
Correct, nothing strict and there is no some `standard` way, they usually just pack a bunch of images in archive and rename that file based on archive type.

**Comment by bakape** [comment]
Okay, so the implementation plan should be 
- [ ] Mime type detection for ZIP, RAR and 7zip archives (already have ZIP and 7z matcher functions in meguca - can move them from there) 
- [ ] If archive detected, the matcher should decompress and do an extra check for comic book formats. 90% of root level file MIME types should be images. 
  - [ ] Currently the `Matcher` interface only accepts the first 512 bytes of a file. Need to think of how to implement these secondary decompressive matchers without breaking the API.  
  - [ ] Needs to be piped to disk to conserve memory usage. 
- [ ] Extract first image and pass down the regular pipeline. 

I should be able to do this some time next week.

**Comment by bakape** [comment]
That's CBZ down. Doubt I'll be able to do the other 2 this week.  Most likely on the next.

**Comment by the8472** [comment]
I'm not seeing any size limit for the unzipping. You might want to defend against zip bombs.

**Comment by bakape** [comment]
@the8472 Good point.

**Comment by bakape** [comment]
@the8472 Does checking the uncompressed size inside the file header mitigate the zip bomb, or do I need to limit the amount of bytes read as well?  What do you think a sane limit?

**Comment by the8472** [comment]
That would depend on whether the decompressor checks that the size in the metadata is not exceeded. As a general principle I wouldn't trust it unless the documentation says otherwise.

For the limit I would say one archive entry shouldn't decompress to more than the total upload limit.

**Comment by bakape** [comment]
CBZ and CBR support done. CB7 dropped for lack of a suitable Go library and I'm not writing my own. 
 @gen2brain Feel free to write a library, which does not depend on precompiled binaries and is compatible with Go modules.  
CBT is not even a compressed or standard format, so I won't bother.
