### ISSUE TITLE
Improper file extension detection

### ISSUE THREAD

**Issue by Chiiruno** [bakape/thumbnailer#52]
![Screenshot_20190312_092500](https://user-images.githubusercontent.com/30435868/54208015-2f958280-44a9-11e9-8ae3-f0b1ceb78c75.png)

**Comment by medukatheguca** [comment]
https://github.com/bakape/thumbnailer/blob/0b14c8002954c7a013b38bdb40e6ee10f3ed2c06/archives.go#L113 ext to lowercase will fix the issue

**Comment by bakape** [comment]
Since when are upper case extensions allowed?

**Comment by medukatheguca** [comment]
You can upload an archive with uppercase extensions which I guess doesn't get checked yet by the thumbnailer.

**Comment by bakape** [comment]
There is no reason it should be rejected based on the extension, but I
should also not accommodate user retardation.

**Comment by medukatheguca** [comment]
Here's a reference of an archive of pngs and an archive of PNGs
<img src=https://user-images.githubusercontent.com/35318851/54256352-23093c80-4532-11e9-93a8-d8b26b414b34.jpg height=50% width=50%>

**Comment by bakape** [comment]
PEBCAK

**Comment by Chiiruno** [comment]
Yes, however it's a simple enough fix to accommodate said problem without a real performance penalty.
