### ISSUE TITLE
ffmpeg: Invalid data found when processing input

### ISSUE THREAD

**Issue by Chiiruno** [bakape/thumbnailer#58]
Happens with vp9 webm encoded with `-threads 16 -row-mt 1`
```
[libvpx-vp9 @ 0x7f784c3d7800] Failed to decode frame: Bitstream not supported by this decoder
[libvpx-vp9 @ 0x7f784c3d7800] Additional information: Unsupported bitstream profile
```
Probably need to upgrade to ffmpeg 4.

**Comment by bakape** [comment]
Yes, upgrade FFmpeg.

**Comment by Chiiruno** [comment]
@bakape I was wondering, why not just use https://github.com/dirkvdb/ffmpegthumbnailer for videos?

**Comment by Chiiruno** [comment]
Hm, can't output as webp, and I imagine it's non-trivial to get the image data itself to do that in thumbnailer.

**Comment by Chiiruno** [comment]
Not a bug, it's just that debian buster has an older version of libvpx.
Is there a way to work around this in thumbnailer?

**Comment by Chiiruno** [comment]
Also, this has nothing to do with row-mt most likely, it seems to happen with vp9 video streams converted from h.265.

**Comment by bakape** [comment]
1. `apt build-dep ffmpeg libvpx`
2. Compile and install fresher libvpx
2. Compile and install fresher ffmpeg
3. `go clean --cache`
4. Rebuild project

**Comment by Chiiruno** [comment]
That worked, we should probably add to the readme a minimum version for them.
https://chromium.googlesource.com/webm/libvpx/+/refs/tags/v1.8.1
https://github.com/FFmpeg/FFmpeg/releases/tag/n4.2.1
