### ISSUE TITLE
EOF interpretation

### ISSUE THREAD

**Issue by halfshoe** [bakape/thumbnailer#61]
Good day.
Some time ago I ran into a problem of interaction of your package and minio-go package. There is link to [Issue](https://github.com/minio/minio-go/issues/1252).
I investigated the problem further and found out the following. When minio-go reaches the end of the file, it returns the number of bytes read and the flag EOF. A read callback from your package will certainly interpret this as an error. Maybe it makes sense to change line 218 from the ffmpeg.go file?

Was `if err != nil {`. Now `if err != nil && err != io.EOF {`?

**Comment by bakape** [comment]
I was not passing EOF properly from Go to FFmpeg, escalating it to critical error. Please see, if it works now.

**Comment by halfshoe** [comment]
I think, the solution you proposed is not entirely correct. Reaching the end of the file is normal situation. It will be enough to return the number of bytes read. So maybe dwell on my version? ))

**Comment by bakape** [comment]
I'll need to look into how FFmpeg handles EOF from read and seek callbacks.

**Comment by bakape** [comment]
Corrected to comply with io.Reader spec
in 835d0de1555a61f4d902dcea5d73c225404e5da2
