### ISSUE TITLE
missing At of image.Image

### ISSUE THREAD

**Issue by artvel** [bakape/thumbnailer#62]
Hi there,

just tried to use this awesome library but encountered the following error by doing so:

```
cannot use thumb (type thumbnailer.Thumbnail) as type image.Image in argument to png.Encode:
	thumbnailer.Thumbnail does not implement image.Image (missing At method)
```

I am using the latest version of go 1.14

Thanks for helping.

**Comment by artvel** [comment]
Never mind. Wasn't using v2.

**Comment by paulm17** [comment]
I'm getting the same error.  How did you fix this?  Thanks
