### ISSUE TITLE
Only width is considered when processing

### ISSUE THREAD

**Issue by artvel** [bakape/thumbnailer#63]
**Make height to be considered too as max.**
Example:
`	opts := thumbnailer.Options{
		ThumbDims: thumbnailer.Dims{Width: 300, Height: 120},
	}
`
result: `300x200`

**expected: 180x120`**

**Comment by bakape** [comment]
I see. Never stumbled on this ones as I've always used even thumbnail dimensions.

**Comment by artvel** [comment]
Wow, that was fast.

Awesome!
