### ISSUE TITLE
Printed errors

### ISSUE THREAD

**Issue by artvel** [bakape/thumbnailer#67]
Not sure how serious and helpful the printed errors are like:
```
[mjpeg @ 0x7fc70c680f80] unable to decode APP fields: Invalid data found when processing input
[mjpeg @ 0x7fc70c681880] unable to decode APP fields: Invalid data found when processing input
[mjpeg @ 0x7fc70c88e480] overread 8
[mjpeg @ 0x7fc70c680440] unable to decode APP fields: Invalid data found when processing input
[mjpeg @ 0x7fc70c6808c0] mjpeg: error decoding EXIF data
[mjpeg @ 0x7fc70c6808c0] No JPEG data found in image
[mjpeg @ 0x7fc70c67e000] mjpeg: error decoding EXIF data
[mjpeg @ 0x7fc70c67e000] No JPEG data found in image
```

One thing I know for sure is, they spam the log although a thumbnail was created most of the times.

I would suggest to only print these kind of errors when an `err` in go was returned by the process call, to help track the cause.

What do you think @bakape?
Does that make any sense?

**Comment by bakape** [comment]
These are printed inside the FFmpeg libraries. IIRC I have fine-grained
control over them.

**Comment by bakape** [comment]
* I don't have
