### ISSUE TITLE
Possible to add API to extract nth frame from a video ?

### ISSUE THREAD

**Issue by agnivade** [bakape/thumbnailer#9]
Currently the `processVideo` function returns just the first frame from a video for the thumbnail. I would like to be able to specify the timestamp of the frame I want to return ?

Is this something that can be added ?

Thanks.

**Comment by bakape** [comment]
Not hard, I think. I'll see to it.

**Comment by agnivade** [comment]
Thanks a lot !

**Comment by bakape** [comment]
This should satisfy your use case. If not, feel free to reopen this issue.
